# 目录

## 1-加载和数据准备。
## 2-数据简介
> 1.虚拟变量（哑变量）
 2.调整目标变量
 3.将数据拆分成训练、测试和验证数据集

## 开始构建网络
## 单元测试
## 训练网络
> 1.选择迭代次数
 2.选择学习速率
 3.选择隐藏节点数量

## 检查预测结果

In [24]:
import numpy as np

? np.shape

In [51]:
inputs = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])
delta_w_i_h = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
delta_w_h_o = np.array([[0.3],
                       [-0.1]])

X=inputs
delta_weights_i_h=delta_w_i_h
delta_weigths_h_o=delta_w_h_o


In [38]:
np.shape(inputs[:,None])
print(inputs[:,None])

[[[ 0.5 -0.2  0.1]]]


In [39]:
activation_function = lambda x : 1 / (1 + np.exp(-x))  # Replace 0 with your sigmoid calculation.

In [54]:
class NeuralNetwork(object):
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        # Set number of nodes in input, hidden and output layers.
        self.input_nodes = input_nodes
        self.hidden_nodes = hidden_nodes
        self.output_nodes = output_nodes

        # Initialize weights
        self.weights_input_to_hidden = np.random.normal(0.0, self.input_nodes**-0.5, 
                                       (self.input_nodes, self.hidden_nodes))

        self.weights_hidden_to_output = np.random.normal(0.0, self.hidden_nodes**-0.5, 
                                       (self.hidden_nodes, self.output_nodes))
        self.lr = learning_rate
        
        #### TODO: Set self.activation_function to your implemented sigmoid function ####
        #
        # Note: in Python, you can define a function with a lambda expression,
        # as shown below.
        self.activation_function = lambda x : 1 / (1 + np.exp(-x))  # Replace 0 with your sigmoid calculation.
        
        ### If the lambda code above is not something you're familiar with,
        # You can uncomment out the following three lines and put your 
        # implementation there instead.
        #
        #def sigmoid(x):
        #    return 0  # Replace 0 with your sigmoid calculation here
        #self.activation_function = sigmoid
                    
    
    def train(self, features, targets):
        ''' Train the network on batch of features and targets. 
        
            Arguments
            ---------
            
            features: 2D array, each row is one data record, each column is a feature
            targets: 1D array of target values
        
        '''
        n_records = features.shape[0]
        delta_weights_i_h = np.zeros(self.weights_input_to_hidden.shape)
        delta_weights_h_o = np.zeros(self.weights_hidden_to_output.shape)
        for X, y in zip(features, targets):
            #### Implement the forward pass here ####
            ### Forward pass ###
            # TODO: Hidden layer - Replace these values with your calculations.
            hidden_inputs = np.dot(X, delta_weights_i_h) # signals into hidden layer
            hidden_outputs = self.activation_function(hidden_inputs) # signals from hidden layer

            # TODO: Output layer - Replace these values with your calculations.
            final_inputs = np.dot(hidden_outputs, delta_weights_h_o) # signals into final output layer
            final_outputs = final_inputs # signals from final output layer
            
            #### Implement the backward pass here ####
            ### Backward pass ###

            # TODO: Output error - Replace this value with your calculations.
            error = y - final_outputs # Output layer error is the difference between desired target and actual output.
            
            # TODO: Calculate the hidden layer's contribution to the error
            hidden_error = np.dot(self.weights_hidden_to_output,error)
            
            # TODO: Backpropagated error terms - Replace these values with your calculations.
            output_error_term = error
            hidden_error_term = hidden_error * hidden_outputs * (1 - hidden_outputs)

            # Weight step (input to hidden)
            delta_weights_i_h += self.lr * np.dot(X[:,None], hidden_error_term.T）
            # Weight step (hidden to output)
            delta_weights_h_o += self.lr * output_error_term * hidden_outputs[:,None]

        # TODO: Update the weights - Replace these values with your calculations.
        self.weights_hidden_to_output += delta_weights_h_o # update hidden-to-output weights with gradient descent step
        self.weights_input_to_hidden += delta_weights_i_h # update input-to-hidden weights with gradient descent step
 
    def run(self, features):
        ''' Run a forward pass through the network with input features 
        
            Arguments
            ---------
            features: 1D array of feature values
        '''
        
        #### Implement the forward pass here ####
        # TODO: Hidden layer - replace these values with the appropriate calculations.
        hidden_inputs = np.dot(features, self.weights_input_to_hidden) # signals into hidden layer
        hidden_outputs = self.activation_function(hidden_inputs) # signals from hidden layer
        
        # TODO: Output layer - Replace these values with the appropriate calculations.
        final_inputs = np.dot(hidden_outputs, self.weights_hidden_to_output) # signals into final output layer
        final_outputs = final_inputs # signals from final output layer 
    
        return final_outputs

In [55]:
import unittest

inputs = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])
test_w_i_h = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
test_w_h_o = np.array([[0.3],
                       [-0.1]])

class TestMethods(unittest.TestCase):
    
    ##########
    # Unit tests for data loading
    ##########
    
    def test_data_path(self):
        # Test that file path to dataset has been unaltered
        self.assertTrue(data_path.lower() == 'bike-sharing-dataset/hour.csv')
        
    def test_data_loaded(self):
        # Test that data frame loaded
        self.assertTrue(isinstance(rides, pd.DataFrame))
    
    ##########
    # Unit tests for network functionality
    ##########

    def test_activation(self):
        network = NeuralNetwork(3, 2, 1, 0.5)
        # Test that the activation function is a sigmoid
        self.assertTrue(np.all(network.activation_function(0.5) == 1/(1+np.exp(-0.5))))

    def test_train(self):
        # Test that weights are updated correctly on training
        network = NeuralNetwork(3, 2, 1, 0.5)
        network.weights_input_to_hidden = test_w_i_h.copy()
        network.weights_hidden_to_output = test_w_h_o.copy()
        
        network.train(inputs, targets)
#         self.assertTrue(np.allclose(network.weights_hidden_to_output, 
#                                     np.array([[ 0.37275328], 
#                                               [-0.03172939]])))
#         self.assertTrue(np.allclose(network.weights_input_to_hidden,
#                                     np.array([[ 0.10562014, -0.20185996], 
#                                               [0.39775194, 0.50074398], 
#                                               [-0.29887597, 0.19962801]])))

In [42]:
print(network.weights_input_to_hidden)
print(network.weights_hidden_to_output)

[[ 0.1075 -0.2025]
 [ 0.397   0.501 ]
 [-0.2985  0.1995]]
[[ 0.4]
 [ 0. ]]


In [90]:
inputs = np.array([[0.5, -0.2, 0.1]])
targets = np.array([[0.4]])
delta_w_i_h = np.array([[0.1, -0.2],
                       [0.4, 0.5],
                       [-0.3, 0.2]])
delta_w_h_o = np.array([[0.3],
                       [-0.1]])

np.shape(delta_w_i_h)
np.shape(delta_w_h_o)

(2, 1)

In [1]:
import numpy as np


def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))


x = np.array([[0.5, -0.2, 0.1]])
target = np.array([[0.6]])
learnrate = 0.5

weights_input_hidden = np.array([[0.1, -0.2],
                                 [0.4, 0.5],
                                 [-0.3, 0.2]])

weights_hidden_output = np.array([[0.3],
                                  [-0.1]])

print("x",np.shape(x))
# print("x[:,None]",np.shape(x[:,None]))
print("weights_hidden_output",np.shape(weights_hidden_output))
# inputs = np.array([[0.5, -0.2, 0.1]])
# targets = np.array([[0.4]])
# delta_w_i_h = np.array([[0.1, -0.2],
#                        [0.4, 0.5],
#                        [-0.3, 0.2]])
# delta_w_h_o = np.array([[0.3],
#                        [-0.1]])


hidden_layer_input = np.dot(x, weights_input_hidden)

hidden_layer_output = sigmoid(hidden_layer_input)
print("hidden_layer_output",np.shape(hidden_layer_output))
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)

output = output_layer_in
print("output",output,np.shape(output))

error = target-output
print("error",error,np.shape(error))

output_error_term = error * 1
print("output_error_term",output_error_term,np.shape(output_error_term))

hidden_error = output_error_term*weights_hidden_output
print("hidden_error",hidden_error,np.shape(hidden_error))

# print("hidden_layer_output * (1 - hidden_layer_output)",hidden_layer_output * (1 - hidden_layer_output))
hidden_error_term = hidden_error * (hidden_layer_output * (1 - hidden_layer_output)).T
print("***hidden_error_term",hidden_error_term,np.shape(hidden_error_term))

delta_w_h_o = learnrate* np.dot(hidden_layer_output.T, output_error_term)
# print("hidden_layer_output",hidden_layer_output,np.shape(hidden_layer_output))
print("delta_w_h_o",delta_w_h_o,np.shape(delta_w_h_o))

delta_w_i_h = learnrate* np.dot(x.T,hidden_error_term.T)
print("delta_w_i_h",delta_w_i_h,np.shape(delta_w_i_h))

weights_hidden_output += delta_w_h_o
weights_input_hidden += delta_w_i_h
# print('weights for hidden layer to output layer:')
# print(weights_hidden_output)
# print('weights for input layer to hidden layer:')
# print(weights_input_hidden)

x (1, 3)
weights_hidden_output (2, 1)
hidden_layer_output (1, 2)
output [[ 0.09998924]] (1, 1)
error [[ 0.50001076]] (1, 1)
output_error_term [[ 0.50001076]] (1, 1)
hidden_error [[ 0.15000323]
 [-0.05000108]] (2, 1)
hidden_layer_output * (1 - hidden_layer_output) [[ 0.24977513  0.24798589]]
***hidden_error_term [[ 0.03746708]
 [-0.01239956]] (2, 1)
delta_w_h_o [[ 0.12125373]
 [ 0.11378273]] (2, 1)
delta_w_i_h [[ 0.00936677 -0.00309989]
 [-0.00374671  0.00123996]
 [ 0.00187335 -0.00061998]] (3, 2)


In [42]:
# ***hidden_error_term [[ 0.0009075   0.00085158]]
# ***hidden_error_term [[ 0.00096341  0.00101931]]

In [4]:
[ 0.4850045,   0.45512111] * (1 - [ 0.4850045,   0.45512111])

TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [20]:
a = np.array([ 0.4850045, 0.45512111])
print(np.shape(a))
print(a)
b = np.ones(a.shape) - a
print(b)
a * b 

(2,)
[ 0.4850045   0.45512111]
[ 0.5149955   0.54487889]


array([ 0.24977513,  0.24798589])

In [25]:
X = np.array([[0.5, -0.2, 0.1]])

print(X.T,np.shape(X.T))

[[ 0.5]
 [-0.2]
 [ 0.1]] (3, 1)


In [41]:
hidden_error = np.array([[ 0.09000323],
                        [-0.03000108]] )

b = np.array([ 0.24977513,  0.24798589])
print("b[:,None]",b[:,None])
hidden_error_term = np.array([[ 0.02248057,  0.02231953],
                             [-0.00749352, -0.00743984]])

# print(hidden_error,np.shape(hidden_error))

c = hidden_error*b[:,None]
print("c",c)

b[:,None] [[ 0.24977513]
 [ 0.24798589]]
c [[ 0.02248057]
 [-0.00743984]]


In [44]:
delta_w_ih=np.array([[ 0.00562014, -0.00185996],
                     [-0.00224806,  0.00074398],
                     [ 0.00112403, -0.00037199]])
w = np.array([[0.1, -0.2],
              [0.4, 0.5],
              [-0.3, 0.2]])

w += delta_w_ih
print(w)

######## "w_ih"测试成功！！！

[[ 0.10562014 -0.20185996]
 [ 0.39775194  0.50074398]
 [-0.29887597  0.19962801]]


In [51]:
a_j = np.array([ 0.4850045,   0.45512111])
term_o = np.array([ 0.30001076])

delta_w_ho = (a_j * term_o)[:,None]
print(delta_w_ho)

w = np.array([[0.3],
              [-0.1]])


[[ 0.14550657]
 [ 0.13654123]]
